# Generated by Django 5.2.7 on 2026-02-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador_id', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
                ('duracion_minutos', models.IntegerField()),
                ('intensidad', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
    ]
